### PR TITLE
Minified, fixed Typo, Updated version

### PR DESCRIPTION
**Pull request by enkodellc**
-Minified disabledSticky updates - dist/sticky.min.js
-Fixed disabled-sticky typo in README.md
-Updated package.json to include 1.7.10

Sorry for the typo.

### CODE REVIEW

**Comment by enkodellc** [comment]
@d-oliveros Please review this update as it definitely fixes my mistakes. Also you should tag the master branch with 1.7.10. Thanks!

**Comment by enkodellc** [comment]
@Fr4nks this PR is done properly, just need to update the github tag version for 1.7.10 when it is merged. Thanks.

**Comment by Fr4nks** [comment]
Oh, just to clarify, sticky.min.js did not include something like
'disabled: '=disabledSticky'' or the minification broke the code.
I've used the functionality by just using the unminified code.
Thanks for the code, works good otherwise.

**Comment by enkodellc** [comment]
The previous PR had a typo. This PR fixed the typo, updated the minification and version. The current  code is broken. This PR fixes it and updates the demo as well. Please merge and add the 1.7.10 github tag to fix the issues. Thanks

**Pull request closed without merging**
